name: cmake-build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        mpi_impl: [mpich, ompi]
        cxx_std: [23, 20]
    steps:
      - uses: actions/checkout@v4
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi_impl }}
      - name: Configure CMake
        env:
          BRIEFKASTEN_CI_USE_CXX23: ${{ matrix.cxx_std == '23' && 'ON' || 'OFF' }}
        run: cmake --preset github-ci -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DBRIEFKASTEN_USE_CXX23=${{ env.BRIEFKASTEN_CI_USE_CXX23 }}

      - name: Build
        run: cmake --build --preset github-ci

      - name: Test
        run: ctest --preset github-ci
